#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -fvg
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_cp "$PWD/tag-zsh/config/zsh/git-prompt.zsh" "$HOME/.config/zsh/git-prompt.zsh"
handle_file_ln "$PWD/tag-zsh/zshenv" "$HOME/.zshenv"
handle_file_ln "$PWD/tag-zsh/zshrc" "$HOME/.zshrc"
handle_file_cp "$PWD/tag-dmz/config/workrc/adminapi.zsh" "$HOME/.config/workrc/adminapi.zsh"
handle_file_cp "$PWD/tag-dmz/config/workrc/arch.sh" "$HOME/.config/workrc/arch.sh"
handle_file_cp "$PWD/tag-dmz/config/workrc/igvm.sh" "$HOME/.config/workrc/igvm.sh"
handle_file_cp "$PWD/tag-dmz/config/workrc/repos-hosts.sh" "$HOME/.config/workrc/repos-hosts.sh"
handle_file_cp "$PWD/tag-dmz/config/workrc/serveradmin.sh" "$HOME/.config/workrc/serveradmin.sh"
handle_file_ln "$PWD/tag-vim/vim" "$HOME/.vim"
handle_file_ln "$PWD/tag-vim/vimrc" "$HOME/.vimrc"
handle_file_ln "$PWD/tag-tmux/tmux.conf" "$HOME/.tmux.conf"
handle_file_ln "$PWD/bashrc" "$HOME/.bashrc"
handle_file_ln "$PWD/config/alacritty" "$HOME/.config/alacritty"
handle_file_ln "$PWD/config/git" "$HOME/.config/git"
handle_file_ln "$PWD/config/shells" "$HOME/.config/shells"
handle_file_cp "$PWD/config/systemd/user/ssh-agent.service" "$HOME/.config/systemd/user/ssh-agent.service"
handle_file_ln "$PWD/config/terminator" "$HOME/.config/terminator"
handle_file_ln "$PWD/ctags.d" "$HOME/.ctags.d"
handle_file_ln "$PWD/pam_environment" "$HOME/.pam_environment"
handle_file_ln "$PWD/rcrc" "$HOME/.rcrc"
handle_file_ln "$PWD/standalone_rcup.sh" "$HOME/.standalone_rcup.sh"
handle_file_ln "$PWD/xinitrc" "$HOME/.xinitrc"
