#!/bin/bash
# PATH
[[ $PATH == *"$HOME/bin"* ]] || export PATH=$PATH:$HOME/bin

# GO
export GOPATH=$HOME/OPT/go
export GOROOT="/usr/lib/go"

# EDITOR
export EDITOR=vim
export VISUAL=vim

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  if [ -r ~/.dircolors ]
    then eval "$(/usr/bin/dircolors -b ~/.dircolors)"
    else eval "$(/usr/bin/dircolors -b)"
  fi
  alias ls='ls --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# keychain, only if SSH_* undefined
[ -x /usr/bin/keychain ] && /usr/bin/keychain --timeout 59 "$HOME"/.ssh/*_rsa -q
if [ -z "$SSH_AUTH_SOCK" ] || [ ! -S "$SSH_AUTH_SOCK" ]; then
  [ -f "$HOME/.keychain/$(hostname -s)-sh" ] && . "$HOME/.keychain/$(hostname -s)-sh"
fi

# password generator
genpasswd() {
  local l=$1
  [[ "$l" == "" ]] && l=16
  tr -dc 'A-Za-z0-9_!@#$%^&*()' < /dev/urandom | head -c ${l} | xargs
}

# work rcs
if [ -r "$HOME/.config/workrc/" ] \
    && [ -n "$(ls "$HOME/.config/workrc/"*.sh)" ]; then
  for src in "$HOME/.config/workrc/"*.sh; do
    [ -r "$src" ] && . "$src"
  done
fi

alias hssh='ssh -NL 10022:localhost:10022 -L 11022:localhost:11022 -L 5432:localhost:5432 -D3333 felixoid.com'

#gnupg.vim
GPG_TTY="$(tty)"
export GPG_TTY

#english git
alias git="LC_ALL=en_US.UTF-8 git"

# docker build cont
dobuild() {
  docker run -w "$(pwd)" --network=host -e GPG_TTY="$GPG_TTY" -e SSH_AUTH_SOCK="$SSH_AUTH_SOCK" -v "$SSH_AUTH_SOCK":"$SSH_AUTH_SOCK" -e HOME:"$HOME" -v /home:/home -u "$UID":"$GID" -v /etc/passwd:/etc/passwd -v "$(pwd):$(pwd)" --rm -it debuild:"${REL:-jessie}" "$@"
}
dorun() {
  docker run -w "$(pwd)" --network=host -e GPG_TTY="$GPG_TTY" -e SSH_AUTH_SOCK="$SSH_AUTH_SOCK" -v "$SSH_AUTH_SOCK":"$SSH_AUTH_SOCK" -e HOME:"$HOME" -v /home:/home -u "$UID":"$GID" -v /etc/passwd:/etc/passwd -v "$(pwd):$(pwd)" --rm -it "$@"
}

# less pipe
export LESSOPEN="|/usr/bin/lesspipe.sh %s"
export LESS_ADVANCED_PREPROCESSOR=1
